### ISSUE TITLE
Cannot discover other nodes

### ISSUE THREAD

**Issue by yanns** [clockworksoul/helm-elasticsearch#3]
When deploying the chart:
```
helm install --name my-release helm-elasticsearch
```
I see the following errors  on all pods:
```
[2017-07-19T13:40:23,055][WARN ][o.e.d.z.UnicastZenPing   ] [my-release-elasticsearch-master-2563649885-55b98] failed to resolve host [my-release-elasticsearch-discovery]
java.net.UnknownHostException: my-release-elasticsearch-discovery
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_131]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_131]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_131]
	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:921) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:876) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:691) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:212) ~[elasticsearch-5.5.0.jar:5.5.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.5.0.jar:5.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

The discovery service seems to run:
```
kubectl get services
NAME                                 CLUSTER-IP   EXTERNAL-IP   PORT(S)                         AGE
kubernetes                           10.0.0.1     <none>        443/TCP                         16m
my-release-elasticsearch             10.0.0.155   <pending>     9200:30709/TCP,9300:30068/TCP   2m
my-release-elasticsearch-discovery   10.0.0.231   <none>        9300/TCP                        2m
```

**Comment by clockworksoul** [comment]
Hi Yanns! Sorry to hear about your issue. At this early stage it _seems_ like it's a DNS issue. Would you mind running through the DNS tests in https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ ?

**Comment by yanns** [comment]
Thx for the very quick answer. 😍 

You're right, I seem to have a DNS issue:
```
kubectl exec -ti busybox -- nslookup kubernetes.default
Server:    10.0.0.10

Address 1: 10.0.0.10

nslookup: can't resolve 'kubernetes.default'
```
👍 

Now that I know what is the problem, I'll try to fix it.
